[package]
name = "klump"
version = "0.1.0"
edition = "2021"

[dependencies]
fjall = "3.0.1"
scru128 = { version = "3", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
blake3 = "1"
data-encoding = "2.6"
